config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact',to: 'pages#contact'
  get 'blog', to: 'posts#index'

  devise_for :users
  
  resources :users, only: [:index, :show]

  resources :posts, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  
  validates :title, 
            presence: true, 
            uniqueness: true, 
            length: {minimum: 3, maximum: 200}
  validates :content, 
            presence: true, 
            length: {minimum: 7, maximum: 3000}
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: :true, uniqueness: { case_sensitive: false }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

  attr_writer :login

  def login
    @login || self.user_name || self.email
  end


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:user_name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:user_name, :email])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :email, :password, :password_confirmation, :current_password])
  end

  def user_allowed(post)
    unless current_user.id == post.user.id
      flash[:danger] = "Permission Denied, You are not the author of this post!"
      redirect_to post_path(@post)
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.limit(4).order('created_at desc')
  end

  def about
  end

  def contact
  end

  def blog
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pagy::Backend
  before_action :post_find, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action -> { user_allowed(@post) }, except: [:index, :show, :new, :create]
  
  def index
    @pagy, @posts = pagy(Post.all.order('created_at desc'), items: 3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Post created successfully."
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    # if current_user.id != @post.user_id 
    #   flash[:danger] = "Yoou are not authorized to edit this post."
    #   redirect_to post_path(@post)
    # end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated successfully"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = "Post deleted successfully"
    redirect_to blog_path
  end


  private
  def post_find
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
        #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= "#{name}" %> alert-dismissible fade show mt-5" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <strong><%= msg %></strong>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Krub:300,400,500,700" rel="stylesheet">
  </head>

  <body>
    <%= render  "shared/navbar" %>
    <div class="container mt-5">
      <%= render  "layouts/messages" %>
      <%= yield %>
    </div>
    <footer class="footer bg-secondary py-2 mt-5">
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
  <div class="jumbotron bg-danger text-center w-100">
    <h1 class="display-3 font-weight-bold">Jumbo heading</h1>
    <p class="lead">Jumbo helper text</p>
    <hr class="my-2">
    <p>More info</p>
    <p class="lead">
      <a class="btn btn-outline-light" href="Jumbo action link" role="button">Jumbo action name</a>
    </p>
  </div>
</div>
<div class="mb-3">
  <div clas="col-md-12">
    <h3>Latest posts from blog.</h3>
  </div>
</div>
<div class="row mb-5">
  <% @posts.each do |post| %>
  <div class="col-md-3">
    <div class="card mb-5">
      <% if post.image.attached? %>
        <%= link_to post_path(post) do %>
          <%= image_tag post.image, class: 'card-img-top img-fluid' %>
        <% end  %>
      <% end %>
      <div class="card-body">
        <h6 class="card-title font-weight-bold">
          <%= link_to post.title, post_path(post) %>
        </h6>
        <p class="card-text">
          <%= truncate(post.content, length: 50) %>
        </p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= time_ago_in_words(post.created_at) %> Ago</small>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/_forms.html.erb
<%= render "shared/errors" %>
<%= form_for @post do |f| %>
  <div class="form-group">
      <%= f.text_field :title, class: 'form-control', placeholder: 'title' %>
  </div>
  <div class="form-group">
      <%= f.file_field :image, class: 'file-control', placeholder: 'Image' %>
  </div>
  <div class="form-group">
      <%= f.text_area :content, class: 'form-control', size: '10x10', placeholder: 'Post Content'%>
  </div>
  <%= f.submit(@post.new_record? ? "Publish" : "Update Post", class: 'btn btn-success btn-sm') %>
  <%= link_to 'Cancle', blog_path, class: 'btn btn-warning btn-sm' %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-8 offset-md-2">
  <h1 class="mb-5">Update post</h1>
  <%= render "forms" %>
</div>

app/views/posts/index.html.erb
<div class="row my-5">
  <div class="col-md-12">
    <% @posts.each do |post| %>
    <div class="card mb-5">
      <div class="row">
        <div class="col-md-4">
          <% if post.image.attached? %>
            <%= image_tag post.image, class: 'img-fluid' %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h6 class="card-title font-weight-bold">
              <%= link_to post.title, post_path(post) %> 
            </h6>
            <p class="card-text">
              <%= truncate(post.content, length: 100) %>
            </p>
          </div>
          <div class="card-footer">
            <small class="text-white badge badge-info"><%= time_ago_in_words(post.created_at) %> Ago</small>
            <small class="text-white badge badge-info">
              Posted By: 
              <%= post.user.user_name %>
            </small>
            <% if user_signed_in? && current_user.id == post.user_id %>
              <%= link_to  "Edit", edit_post_path(post), class: 'btn btn-sm btn-primary ml-3' %>
              <%= link_to  "Delete", post_path(post), method: :delete, data: {Confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <%== pagy_nav_bootstrap(@pagy) %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="col-md-8 offset-md-2">
  <h1 class="mb-5">Create new post</h1>
  <%= render "forms" %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card mb-5">
      <div class="card-header">
        <% if @post.image.attached? %>
          <%= image_tag @post.image, class: 'img-fluid' %>
        <% end %>
      </div>
      <div class="card-body">
        <h4 class="card-title"><%= @post.title %></h4>
        <p class="card-text"><%= simple_format(@post.content) %></p>
      </div>
      <div class="card-footer text-muted">
        <span class="badge p-2 badge-primary">Published <%= time_ago_in_words(@post.created_at) %> Ago</span> 
        <%= link_to  "Back to blog", blog_path, class: 'btn btn-sm btn-warning ml-2' %>
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <%= link_to  "Edit", edit_post_path(@post), class: 'btn btn-sm btn-success ml-2' %>
          <%= link_to  "Delete", post_path(@post), method: :delete, data: {Confirm: "Are you sure?"}, class: 'btn btn-sm btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
    </button>
    <h5 class="mb-3">The Following
      <%= pluralize(@post.errors.count, 'errors') %>
      Preventing this post to be published.
    </h5>
    <ul class="list-group list-group-flush">
      <% @post.errors.full_messages.each do |msg| %> 
        <li class="list-group-item"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-12">
      <span class="text-white">All right reserved &copy; 2018 
        <%= link_to 'sm ehsan', root_path, class: 'text-danger' %>
      </span>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-secondary sticky-top">
  <div class="container">
    <%= link_to  "Simple Blog", root_path, class: 'navbar-brand' %>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to  "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to  "About", about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to  "Contact", contact_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to  "blog", blog_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdownId">
          <% if user_signed_in? %>
            <%= link_to  "Profile", user_path(current_user), class: 'dropdown-item' %>
            <%= link_to  "New Post", new_post_path, class: 'dropdown-item' %>
            <%= link_to  "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to  "Sign In", new_user_session_path, class: 'dropdown-item' %>
            <%= link_to  "Sign Up", new_user_registration_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class="row">
  <% @users.each do |u| %>
  <div class="col-md-4">
    <div class="card mb-3">
      <img class="card-img-top" src="holder.js/100px180/" alt="">
      <div class="card-body">
        <h4 class="card-title"><%= link_to u.user_name, user_path(u) %></h4>
        <p class="card-text"><%= link_to u.email %></p>
      </div>
      <div class="card-footer">
        <span>Number of posts</span>
        <strong><%= u.posts.count %></strong>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card bg-warning>
      <img class="card-img-top" src="holder.js/100px180/" alt="">
      <div class="card-body">
        <h4 class="card-title"><%= @user.user_name %></h4>
        <p class="card-text"><%= @user.email %></p>
        <% if user_signed_in? && (current_user.id == @user.id) %>
          <%= link_to  "Edit Profile", edit_user_registration_path %>
        <% end %>
      </div>
      <div class="card-footer">
        <span>Number of posts</span>
        <strong><%= @user.posts.count %></strong>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-12">
        <h2>Posts created By <%= @user.user_name %> </h2>
      </div>
      <% @user.posts.each do |p| %>
      <div class="col-md-4">
        <div class="card bg-warning mb-3">
          <img class="card-img-top" src="holder.js/100px180/" alt="">
          <div class="card-body">
            <h6 class="card-title"><%= p.title %></h6>
            <p class="fs-sm card-text"><%= truncate(p.content, length: 100) %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>